spring:
  profiles:
    active: local #local,dev,real... 환경 설정
           #입력 시 한 칸 띄워줘야!
      
  datasource: #DB 접속
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: c##user001
    password: 1234
    hikari:      connection-timeout: 30000 #클라이언트가 pool에 connection을 요청하는데 기다리는 최대 시간을 설정 (30000밀리세컨드=30초)
      maximum-pool-size: 10 #최대 커넥션 개수 설정
      max-lifetime: 1800000 #커넥션 풀에서 살아있을 수 있는 커넥션의 최대 수명 시간 (1,800초=30분)
      
  messages: #메시지 처리    basename: messages.validation
    encoding: UTF-8
    
  devtools: #View reload    livereload:      enabled: true
    restart: #컨트롤러,모델단이 바뀌었을 때 프로젝트 재시작 설정 (정확히는 classpath에 있는 모든 파일)      enabled: true

  thymeleaf:    prefix: classpath:templates/views/
    suffix: .html
    check-template-location: true
    mode: HTML5
      
mybatis: #mybatis 설정  type-aliases-package: kr.spring.**.vo #하위패키지를 **로 명시 - 모두 적용되어 일일히 쓸 필요 없어짐
  mapper-locations: kr/spring/**/dao/*.xml
  
logging: #로그 지정  level:
    '[kr.spring]': debug
    
server:  port: 8000 #포트 - 8080에서 8000으로 변경
  servlet:
    encoding:      charset: UTF-8
      enabled: true #http 인코딩 지원을 활성화할 지 여부
      force: true
